version: '3.4'

services:
  gamemanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__GameManagementContext=Server=sqlserver;database=GameManagementContext;User Id=sa;password=P@ssw0rd;Max Pool Size=200;Connection Timeout=120;
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro