// <auto-generated />

using GameManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace GameManagement.Migrations
{
    [DbContext(typeof(GameManagementContext))]
    internal class GameManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameManagement.Models.Game", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Games");
            });

            modelBuilder.Entity("GameManagement.Models.GamePlatform", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("GameId")
                    .HasColumnType("int");

                b.Property<int>("PlatformId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("GameId");

                b.HasIndex("PlatformId");

                b.ToTable("GamePlatforms");
            });

            modelBuilder.Entity("GameManagement.Models.Platform", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Platforms");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "PC"
                    },
                    new
                    {
                        Id = 2,
                        Name = "PS4"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Nintendo Switch"
                    });
            });

            modelBuilder.Entity("GameManagement.Models.GamePlatform", b =>
            {
                b.HasOne("GameManagement.Models.Game", "Game")
                    .WithMany("GamePlatforms")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GameManagement.Models.Platform", "Platform")
                    .WithMany("GamePlatforms")
                    .HasForeignKey("PlatformId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}